[package]
name = "kernels"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
shared_structs = { path = "../shared_structs" }
spirv-std = "0.9.0"

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
rayon = "1.5"
